sudo: false
language: python
notifications:
  email: false
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - pypy
before_install:
  - pip install -r tests/requirements.txt
script:
  - make test
  - make -C examples
  - make -C examples/robotchef_allinone
  - make -C examples/robotchef_allinone_lml
  - make -C examples/v2
after_success:
  codecov
